id = "blox-mono-theme"
name = "Blox Monochrome Theme"
version = "0.1.0"
schema_version = 1
description = "A monochrome theme for Zed."
authors = ["Zebrakat"]
themes = ["themes/blox.json"]
repository = "https://github.com/4teapo/zed-luau"
icon_themes = []
languages = []

[lib]
[grammars]
[language_servers]
[context_servers]
[slash_commands]
[indexed_docs_providers]
